menu:
  首页: /
  归档: /archives
  关于: /about
subtitle: Collect the dots in your life.

widgets:
- search
- tagcloud
- recent_posts
- tag
- blogroll

excerpt_link: 阅读全文

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: false
  google: false
  pinterest: true

fancybox: true

rss: /atom.xml
